import { env } from "@repo/env";

const IMAGE_WIDTH = env.IMAGE_WIDTH;
const IMAGE_HEIGHT = env.IMAGE_HEIGHT;
const IMAGE_URL = `https://picsum.photos/${IMAGE_WIDTH}/${IMAGE_HEIGHT}`;
const MIN_POLYGON_POINTS = 3;
const POLYGON_COLOR = "#2563eb";
const POLYGON_TRANSPORT = env.NEXT_PUBLIC_POLYGON_TRANSPORT;

export { IMAGE_HEIGHT, IMAGE_URL, IMAGE_WIDTH, MIN_POLYGON_POINTS, POLYGON_COLOR, POLYGON_TRANSPORT };
